#' Save QMD to a file
#'
#' @description Save QMD to different file formats
#'
#' @param qmd_graph A qmd object generated by \code{render_graph}
#' @param title A title to be added to the graph
#' @param filename Name of the file to be created on the disk without the extension
#' @param device Device to use, can be "pdf", "ps", "jpeg", "png", or "svg"
#' @param width width of the output in pixels
#' @param height height of the output in pixels
#'
#' @export
save_qmd <- function(qmd_graph = NULL,
                     title     = NULL,
                     filename  = 'qmd_graph',
                     width     = NULL,
                     height    = NULL,
                     device    = 'pdf') {


  # Check inputs ------------------------------------------------------------
  if (is.null(qmd_graph)) {
    stop('Argument \"qmd_graph\" required.')
  }

  if (!tolower(device) %in% c('pdf', 'eps', 'ps', 'postscript',
                              'jpeg', 'jpg', 'png', 'svg')) {
    stop('Invalid \"device\" argument.')
  }

  if (is.null(width) & is.null(height)) { width <- 1000 }


  # Prepare raw output ------------------------------------------------------
  raw <- DiagrammeR::render_graph(qmd_graph, title = title)
  raw <- DiagrammeRsvg::export_svg(raw)
  raw <- charToRaw(raw)


  # Save file to desired format ---------------------------------------------
  if (tolower(device) == 'svg') {
    rsvg::rsvg_svg(svg    = raw,
                   file   = paste0(filename, '.svg'),
                   width  = width,
                   height = height)
  }

  if (tolower(device) == 'pdf') {
    rsvg::rsvg_pdf(svg    = raw,
                   file   = paste0(filename, '.pdf'),
                   width  = width,
                   height = height)
  }

  if (tolower(device) %in% c('eps', 'ps', 'postscript')) {
    rsvg::rsvg_ps(svg    = raw,
                  file   = paste0(filename, '.ps'),
                  width  = width,
                  height = height)
  }

  if (tolower(device) == 'png') {
    rsvg::rsvg_png(svg    = raw,
                   file   = paste0(filename, '.png'),
                   width  = width,
                   height = height)
  }

  if (tolower(device) %in% c('jpg', 'jpeg')) {
    jpg <- rsvg::rsvg(svg    = raw,
                      width  = width,
                      height = height)

    jpeg::writeJPEG(image   = jpg,
                    target   = paste0(filename, '.jpg'),
                    quality = 1)
  }
}
